spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.110.152.217:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
      maximum-pool-size: 20
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 47.110.152.217

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 7000

logging:
  level:
    io.niceseason.gulimall.coupon.dao: debug