spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: #
  redis:
    host: 192.168.56.102
  session:
    store-type: redis

server:
  port: 20000
  servlet:
    session:
      timeout: 30m
