server:
  port: 12000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: #
  redis:
    host: 192.168.56.102
  session:
    store-type: redis
logging:
  level:
    io.niceseason.gulimall.search.service: debug