spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.110.152.217:8848
    alicloud:
      access-key: LTAI4G36rcBvn3uGH4RgW9QL
      secret-key:  8hbKqxS9oA7AsVcdmLDKeCrlSyGpJb
      oss:
        bucket: gulimall-niceseason
        endpoint: oss-cn-hangzhou.aliyuncs.com
      # 发送短信接口的配置
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        appcode: 0a118f8b1b3d43d5b10732a6caad9e0d

  application:
    name: gulimall-third-party

server:
  port: 30000



