spring:
  cloud:
    nacos:
      discovery:
        server-addr: #:8848
    alicloud:
      access-key: #
      secret-key:  #
      oss:
        bucket: gulimall-niceseason
        endpoint: oss-cn-hangzhou.aliyuncs.com
      # 发送短信接口的配置
      sms:
        host: #
        path: #
        appcode: #

  application:
    name: gulimall-third-party

server:
  port: 30000



